GET http://localhost:8080/users

###

GET http://localhost:8080/users/622cccd4bffb4f5279f5f15c

###

POST http://localhost:8080/users
Content-Type: application/json

{
    "username":"Koshek",
    "email":"tea.zup@gmail.com",
    "password":"lillol123"
}

###

DELETE http://localhost:8080/users/62262f73e7bbf240cc85b2e4

###
POST http://localhost:8080/users